export module Ogre.Core:StdHeaders;

export import <algorithm>;
export import <atomic>;
export import <cmath>;
export import <cstdarg>;
export import <cstdio>;
export import <cstdlib>;
export import <cstring>;
export import <ctime>;
export import <iosfwd>;
export import <list>;
export import <map>;
export import <ostream>;
export import <set>;
export import <sstream>;
export import <string>;
export import <unordered_map>;
export import <vector>;
